# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threeD', '0002_threed_create_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='threeD',
        ),
    ]
