# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threeD', '0003_delete_threed'),
    ]

    operations = [
        migrations.CreateModel(
            name='threeD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateField(blank=True, null=True)),
                ('order', models.CharField(max_length=7)),
                ('three_d', models.CharField(max_length=3)),
            ],
        ),
    ]
